package ca.uwo.csd.cs2212.team14_fyt.Main;

import java.awt.Color;

/**
 * FoodWater.java
 * 
 * The FoodWater class creates a detail screen that is accessible from
 * the DailyDashboard class. It allows the user to view in greater detail
 * their nutrition information as obtained from the Fitbit API.
 * 
 * @author fyt Team
 * @version 1.0
 * @since March 22, 2016
 */
public class FoodWaterDetail extends javax.swing.JFrame {
    
    private FoodModel food;
    private WaterLogModel water;

    /**
     * Creates new form FoodWater
     */
    public FoodWaterDetail(FoodModel food, WaterLogModel water) {
        this.food = food; 
        this.water = water;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Color[] theme = Configuration.getTheme();
        if (theme == null){
            theme = new Color[2];
            theme[0] = Color.GRAY;
            theme[1] = Color.GRAY;
        }
        Configuration config;
        try{config = Configuration.load();}
        catch (Exception e){config = new Configuration();}
        mainPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        mainText = new javax.swing.JLabel();
        mainSummary = new javax.swing.JPanel();
        summaryHeader = new javax.swing.JLabel();
        calorieLabel = new javax.swing.JLabel();
        carbsLabel = new javax.swing.JLabel();
        fatLabel = new javax.swing.JLabel();
        fibreLabel = new javax.swing.JLabel();
        proteinLabel = new javax.swing.JLabel();
        sodiumLabel = new javax.swing.JLabel();
        waterLabel = new javax.swing.JLabel();
        calorieDisplayLabel = new javax.swing.JLabel();
        carbsDisplayLabel = new javax.swing.JLabel();
        fatDisplayLabel = new javax.swing.JLabel();
        fibreDisplayLabel = new javax.swing.JLabel();
        proteinDisplayLabel = new javax.swing.JLabel();
        sodiumDisplayLabel = new javax.swing.JLabel();
        waterDisplayLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        foodLogHeading = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        foodLog = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        waterLog = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("fyt - Food and Water");
        setResizable(false);

        mainPanel.setBackground(theme[0]);

        jPanel1.setBackground(theme[1]);
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        mainText.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        mainText.setText("Food and Water");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainText)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(mainText)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        mainSummary.setBackground(theme[1]);
        mainSummary.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        summaryHeader.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        summaryHeader.setText("Summary");

        calorieLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        calorieLabel.setText("Calories:");

        carbsLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        carbsLabel.setText("Carbs:");

        fatLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        fatLabel.setText("Fat:");

        fibreLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        fibreLabel.setText("Fiber:");

        proteinLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        proteinLabel.setText("Protein:");

        sodiumLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sodiumLabel.setText("Sodium:");

        waterLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        waterLabel.setText("Water:");

        calorieDisplayLabel.setText(Double.toString(food.getSummaryCalories()) + "kCal");

        carbsDisplayLabel.setText(Double.toString(food.getSummaryCarbs())+ "g");

        fatDisplayLabel.setText(Double.toString(food.getSummaryFat()) + 'g');

        fibreDisplayLabel.setText(Double.toString(food.getSummaryFiber()) + 'g');

        proteinDisplayLabel.setText(Double.toString(food.getSummaryProtein()) + 'g');

        sodiumDisplayLabel.setText(Double.toString(food.getSummarySodium()) + "mmol/L");

        waterDisplayLabel.setText(Double.toString(food.getSummaryWater()) + "mL");

        javax.swing.GroupLayout mainSummaryLayout = new javax.swing.GroupLayout(mainSummary);
        mainSummary.setLayout(mainSummaryLayout);
        mainSummaryLayout.setHorizontalGroup(
            mainSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainSummaryLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(summaryHeader)
                    .addGroup(mainSummaryLayout.createSequentialGroup()
                        .addGroup(mainSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(calorieLabel)
                            .addComponent(carbsLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(fatLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(fibreLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(26, 26, 26)
                        .addGroup(mainSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(calorieDisplayLabel)
                            .addGroup(mainSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(fatDisplayLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(carbsDisplayLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(fibreDisplayLabel, javax.swing.GroupLayout.Alignment.TRAILING)))
                        .addGap(94, 94, 94)
                        .addGroup(mainSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(proteinLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(mainSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(sodiumLabel)
                                .addGroup(mainSummaryLayout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addComponent(waterLabel))))
                        .addGap(27, 27, 27)
                        .addGroup(mainSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sodiumDisplayLabel)
                            .addComponent(waterDisplayLabel)
                            .addComponent(proteinDisplayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        mainSummaryLayout.setVerticalGroup(
            mainSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainSummaryLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(mainSummaryLayout.createSequentialGroup()
                        .addGroup(mainSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(proteinDisplayLabel)
                            .addComponent(proteinLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(mainSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sodiumLabel)
                            .addComponent(sodiumDisplayLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(mainSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(waterLabel)
                            .addComponent(waterDisplayLabel)))
                    .addGroup(mainSummaryLayout.createSequentialGroup()
                        .addComponent(summaryHeader)
                        .addGap(18, 18, 18)
                        .addGroup(mainSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(calorieLabel)
                            .addComponent(calorieDisplayLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(mainSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(carbsLabel)
                            .addComponent(carbsDisplayLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(mainSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fatLabel)
                            .addComponent(fatDisplayLabel))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fibreLabel)
                    .addComponent(fibreDisplayLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.setText("Return to Dashboard");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel2.setBackground(theme[1]);
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setToolTipText("");

        foodLogHeading.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        foodLogHeading.setText("Food Log");

        jScrollPane2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        foodLog.setEditable(false);
        foodLog.setColumns(20);
        foodLog.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        foodLog.setRows(5);
        foodLog.setTabSize(7);
        foodLog.setText(food.multiLogGen());
        jScrollPane2.setViewportView(foodLog);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(foodLogHeading)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jScrollPane2)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(foodLogHeading)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.setBackground(theme[1]);
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setMinimumSize(new java.awt.Dimension(0, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Water Log");

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        waterLog.setEditable(false);
        waterLog.setColumns(20);
        waterLog.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        waterLog.setRows(5);
        waterLog.setTabSize(7);
        waterLog.setText(water.multiLogGen());
        jScrollPane1.setViewportView(waterLog);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mainSummary, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, mainPanelLayout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainSummary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * main method to create this panel
     */
    public void main() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FoodWaterDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FoodWaterDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FoodWaterDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FoodWaterDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FoodWaterDetail(food, water).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel calorieDisplayLabel;
    private javax.swing.JLabel calorieLabel;
    private javax.swing.JLabel carbsDisplayLabel;
    private javax.swing.JLabel carbsLabel;
    private javax.swing.JLabel fatDisplayLabel;
    private javax.swing.JLabel fatLabel;
    private javax.swing.JLabel fibreDisplayLabel;
    private javax.swing.JLabel fibreLabel;
    private javax.swing.JTextArea foodLog;
    private javax.swing.JLabel foodLogHeading;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel mainSummary;
    private javax.swing.JLabel mainText;
    private javax.swing.JLabel proteinDisplayLabel;
    private javax.swing.JLabel proteinLabel;
    private javax.swing.JLabel sodiumDisplayLabel;
    private javax.swing.JLabel sodiumLabel;
    private javax.swing.JLabel summaryHeader;
    private javax.swing.JLabel waterDisplayLabel;
    private javax.swing.JLabel waterLabel;
    private javax.swing.JTextArea waterLog;
    // End of variables declaration//GEN-END:variables
}
